---
# tasks file for 10_deploy_controlplanes
- name: Deploy controlplane
  block:
    - name: Install adm software
      become: true
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      tags:
        - controlplane_software

    - name: Add keys and repo
      block:
        - name: docker key
          become: true
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: kubernetes key
          become: true
          ansible.builtin.apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: docker repo | apt source
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

      tags:
        - controlplane_repo_keys

    - name: Install additional software
      become: true
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - docker-ce
          - kubelet
          - kubeadm
          - kubernetes-cni
      register: kubeadm_install
      tags:
        - controlplane_additional_software

    - name: SWAP OFF
      become: true
      block:
        - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
          shell: |
            swapoff -a

        - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
          replace:
            path: /etc/fstab
            regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
            replace: '# \1'

      when: kubeadm_install.changed
      tags:
        - swap_off

    - name: Deploy
      become: true
      block:
        # https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/
        - name: Reset Kubernetes component
          shell: "kubeadm reset --force"
          register: reset_cluster

        # https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
        - name: Init Kubernetes cluster
          when: reset_cluster is succeeded
          shell: |
            kubeadm init
          register: init_cluster

        - name: Get join string
          ansible.builtin.shell:
            cmd: echo "{{ init_cluster.stdout }}" | grep -A 1 "kubeadm join" > /home/{{ ansible_user }}/node_join_command.log
          when: reset_cluster is succeeded

        - name: Config dir
          file:
            path: ".kube/"
            state: directory

        - name: Copy admin.conf to Home directory
          when: init_cluster is succeeded
          copy:
            src: "{{ kubeadmin_config }}"
            dest: ".kube/config"
            owner: "{{ ansible_user | default(ansible_user_id) }}"
            group: "{{ ansible_user | default(ansible_user_id) }}"
            mode: 0755
            remote_src: true

        # https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
        - name: Dashboard deployment
          when: init_cluster is succeeded
          command: |
            kubectl --kubeconfig={{ kubeadmin_config }} \
                apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.1/aio/deploy/recommended.yaml
          register: create_result
          until: create_result.rc == 0
          retries: 5
          delay: 2
          ignore_errors: true
      tags:
        - kubeadm_init

    # - name: SWAP ON
    #   become: true
    #   block:
    #     - name: Reenable SWAP in fstab (1/2)
    #       replace:
    #         path: /etc/fstab
    #         regexp: '^# (.+?\sswap\s+sw\s+.*)$'
    #         replace: '\1'

    #     - name: Enable SWAP (2/2)
    #       shell: |
    #         swapon -a

  tags:
    - controlplane_deploy
