---
# tasks file for 20_deploy_join_nodes
- name: Deploy node
  block:
    - name: Install adm software
      become: true
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
      tags:
        - node_software

    - name: Add keys and repo
      block:
        - name: google key
          become: true
          ansible.builtin.apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: kubernetes repo | apt source
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
            state: present
      tags:
        - node_additional_software

    - name: Install additional software
      become: true
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - kubelet
          - kubeadm
          - kubectl
      register: kubeadm_install
      tags:
        - node_additional_software

    # https://cri-o.io/
    - name: Install CRI-O
      become: true
      block:
        - name: Add repo \#1
          ansible.builtin.copy:
            content: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/ /"
            dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list

        - name: Add repo \#2
          ansible.builtin.copy:
            content: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ VERSION }}/{{ OS }}/ /"
            dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}.list

        - name: Add an Apt signing key \#1
          ansible.builtin.apt_key:
            url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ VERSION }}/{{ OS }}/Release.key"
            state: present

        - name: Add an Apt signing key \#2
          ansible.builtin.apt_key:
            url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}/Release.key"
            state: present

        - name: Install CRI-O software
          ansible.builtin.apt:
            state: present
            update_cache: yes
            pkg:
              - cri-o
              - cri-o-runc
          register: cri_o_install
          notify: Prepare service

      tags:
        - node_install_cri_o

  tags:
    - node_deploy
